spring:
  profiles:
    active: prod
  application:
    name: club-recruitment
  datasource:
    url: jdbc:mysql://${app.mysql.host}:${app.mysql.port:3306}/${app.mysql.database:club-recruitment}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: ${app.mysql.username}
    password: ${app.mysql.password}
    driver-class-name: ${app.mysql.driver-class-name}
    druid:
      connect-timeout: 3000
      max-pool-prepared-statement-per-connection-size: 20
  data:
    redis:
      host: ${app.redis.host}
      port: ${app.redis.port:6379}
      password: ${app.redis.password}
      database: ${app.redis.database:2}
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 500MB
  threads:
    virtual:
      enabled: true # Java 19引入的虚拟线程
server:
  port: 12321
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml  #指定sql映射文件
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名

springdoc:
  # 默认展开参数
  default-flat-param-object: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cn.luowb.clubrecruitment
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

sa-token:
  token-name: Authorization
  token-prefix: Bearer
  timeout: 1800
  is-concurrent: false
  is-share: false

app:
  mysql:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: ${DATABASE_HOST:127.0.0.1}
    port: ${DATABASE_PORT:3306}
    database: ${DATABASE_NAME:club}
    username: ${DATABASE_USERNAME:}
    password: ${DATABASE_PASSWORD:}
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: ${REDIS_DATABASE:2}
  qiniu:
    access-key: ${QINIU_ACCESS_KEY:}
    secret-key: ${QINIU_SECRET_KEY:}
    bucket: ${QINIU_BUCKET:}
    domain: ${QINIU_DOMAIN:}
  # 点赞防刷时间间隔(秒)
  like-interval-seconds: 86400

