spring:
  profiles:
    active: prod
  application:
    name: club-recruitment
  datasource:
    url: jdbc:mysql://${rec.datasource.host}:${rec.datasource.port:3306}/${rec.datasource.database:club-recruitment}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: ${rec.datasource.username}
    password: ${rec.datasource.password}
    driver-class-name: ${rec.datasource.driver-class-name}
    druid:
      connect-timeout: 3000
      max-pool-prepared-statement-per-connection-size: 20
  data:
    redis:
      host: ${rec.redis.host}
      port: ${rec.redis.port:6379}
      password: ${rec.redis.password}
      database: ${rec.redis.database:2}
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 500MB
server:
  port: 12321
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml  #指定sql映射文件
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名

springdoc:
  # 默认展开参数
  default-flat-param-object: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cn.luowb.clubrecruitment
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

rec:
  # 点赞防刷时间间隔(秒)
  like-interval-seconds: 86400
  # 管理员登录token有效期
  admin-token-expire-minutes: 30
minio:
  endpoint: ${minio.endpoint}
  access-key: ${minio.access-key}
  secret-key: ${minio.secret-key}
  bucket-name: ${minio.bucket-name}

