# 自行将该文件复制一份名为application-dev.yml的文件, 并修改里面的数据库信息, minio信息
# 启动项需要添加有效配置文件为dev, 或直接添加JVM参数: -Dspring.profiles.active=dev
app:
  mysql:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: ${DATABASE_HOST:localhost}
    port: ${DATABASE_PORT:3306}
    database: ${DATABASE_NAME:club-recruitment}
    username: ${DATABASE_USERNAME:}
    password: ${DATABASE_PASSWORD:}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: ${REDIS_DATABASE:2}
  minio:
    endpoint: ${MINIO_ENDPOINT:}
    public-endpoint: ${MINIO_PUBLIC_ENDPOINT:}
    access-key: ${MINIO_ACCESS_KEY:}
    secret-key: ${MINIO_SECRET_KEY:}
    bucket-name: ${MINIO_BUCKET_NAME:club-recruitment}
  # 点赞防刷时间间隔(秒)
  like-interval-seconds: 86400
  # 管理员登录token有效期
  admin-token-expire-minutes: 30
logging:
  level:
    cn.luowb.clubrecruitment.controller: debug
    cn.luowb.clubrecruitment.dao.mapper: debug
    cn.luowb.clubrecruitment.common.util: debug